# Array Operations

NumPy is not just good at storing large amounts of data, it's also very efficient at performing calculations and makes carrying out these calculations very convenient. This notebook discusses some of these calculations and the syntax used to invoke them.

## Arithmetic Operations

Simple arithmetic operators can be performed using NumPy arrays. When such an operation is placed between two NumPy arrays, the operation is performed "element-wise". This means that the operation is performed on each element of the arrays to create the corresponding element of the new array. For instance:

In [1]:
import numpy as np

a = np.array([2,4,6])
b = np.array([1,3,5])

print("Addition: ", a + b)
print("Subtraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Exponentiation: ", a ** b)
print("Integer Division: ", a // b)
print("Modulo: ", a % b)
print("Negative: ", -a)

Addition:  [ 3  7 11]
Subtraction:  [1 1 1]
Multiplication:  [ 2 12 30]
Division:  [2.         1.33333333 1.2       ]
Exponentiation:  [   2   64 7776]
Integer Division:  [2 1 1]
Modulo:  [0 1 1]
Negative:  [-2 -4 -6]


Note that, when operating on arrays in this way, both arrays must be the same dimension and size.

In [2]:
import numpy as np

# These arrays have the same number of elements but a different number of dimensions
a = np.arange(4).reshape([2,2])
b = np.arange(1,5)

print(a + b)

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

## Applying the Same Operation to Every Element

It's possible to apply the same operation to every element of an array using an operator and a scalar value. The array and the integer may be in either order.

In [3]:
import numpy as np

a = np.arange(1, 4)
print("a: ", a)
print("Addition: ", 2 + a)
print("Left Subtraction: ", 2 - a)
print("Right Subtraction: ", a - 2)
print("Multiplication: ", a * 2)
print("Left Division: ", a / 2)
print("Right Division: ", 2 / a)
print("Left Exponentiation: ", 2 ** a)
print("Right Exponentiation: ", a ** 2)
print("Left Integer Division: ", 2 // a)
print("Right Integer Division: ", a // 2)
print("Left Modulo: ", 2 % a)
print("Right Modulo: ", a % 2)

a:  [1 2 3]
Addition:  [3 4 5]
Left Subtraction:  [ 1  0 -1]
Right Subtraction:  [-1  0  1]
Multiplication:  [2 4 6]
Left Division:  [0.5 1.  1.5]
Right Division:  [2.         1.         0.66666667]
Left Exponentiation:  [2 4 8]
Right Exponentiation:  [1 4 9]
Left Integer Division:  [2 1 0]
Right Integer Division:  [0 1 1]
Left Modulo:  [0 0 2]
Right Modulo:  [1 0 1]


## Exercise

Look at the code in the cell below, but don't run it yet. Instead, write down what you think will be printed in each case. Then, run the code and check you get the results you expect.

In [4]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

print("Case 1: ", a + b) # [4, 6]
print("Case 2: ", a / 2) # [0.5, 1]
print("Case 3: ", a ** b) # [1, 16]
print("Case 4: ", 2 - a) # [1, 0]
print("Case 5: ", a - b * 2) # [-5, -6]

Case 1:  [4 6]
Case 2:  [0.5 1. ]
Case 3:  [ 1 16]
Case 4:  [1 0]
Case 5:  [-5 -6]


## More Complex Functions

Many complex mathematical functions which operate on scalars in Python are available from the ```math``` module, such as the ```sin``` function. These functions will work on NumPy arrays with a size of 1 (and return a scalar), but will not work on larger arrays:

In [5]:
import numpy as np
import math

print(math.sin(2))
print(math.sin(np.array([1])))
print(math.sin(np.arange(3)))

0.9092974268256817
0.8414709848078965


TypeError: only size-1 arrays can be converted to Python scalars

Fortunately, many of these functions are replicated within the NumPy array and will operate element-wise on an array passed to it:

In [6]:
import numpy as np

# Here we multiply the array [1 2 3] by a quarter
a = np.arange(1,4) * 0.25
print("a: ", a)
print("sin: ", np.sin(a))
print("arccos: ", np.arccos(a))
print("log: ", np.log(a))
print("log2: ", np.log2(a))
print("log10: ", np.log10(a))
print("sqrt: ", np.sqrt(a))
print("sum: ", np.sum(a))

a:  [0.25 0.5  0.75]
sin:  [0.24740396 0.47942554 0.68163876]
arccos:  [1.31811607 1.04719755 0.72273425]
log:  [-1.38629436 -0.69314718 -0.28768207]
log2:  [-2.        -1.        -0.4150375]
log10:  [-0.60205999 -0.30103    -0.12493874]
sqrt:  [0.5        0.70710678 0.8660254 ]
sum:  1.5


## Vector and Matrix Operations

NumPy is designed to hold vectors, matrices, tensors and so on. It also contains functions to perform common operations relevant to these data types. For instance:

In [7]:
import numpy as np

matrix = np.arange(4).reshape([2,2])
vector1 = np.array([1,2])
vector2 = np.array([3,4])

print("Matrix: ", matrix)
print("Vector1: ", vector1)
print("Vector2: ", vector2)

print("Dot product", np.dot(vector1, vector2))
print("Matrix-vector multiplication: ", np.matmul(matrix, vector1))
print("Matrix-matrix multiplication: ", np.matmul(matrix, matrix))
print("Matrix power: ", np.linalg.matrix_power(matrix, 3))
print("Determinant: ", np.linalg.det(matrix))
print("Transpose: ", np.transpose(matrix))
print("Inverse: ", np.linalg.inv(matrix))
print("Eigenvectors and eigenvalues: ", np.linalg.eig(matrix))

Matrix:  [[0 1]
 [2 3]]
Vector1:  [1 2]
Vector2:  [3 4]
Dot product 11
Matrix-vector multiplication:  [2 8]
Matrix-matrix multiplication:  [[ 2  3]
 [ 6 11]]
Matrix power:  [[ 6 11]
 [22 39]]
Determinant:  -2.0
Transpose:  [[0 2]
 [1 3]]
Inverse:  [[-1.5  0.5]
 [ 1.   0. ]]
Eigenvectors and eigenvalues:  (array([-0.56155281,  3.56155281]), array([[-0.87192821, -0.27032301],
       [ 0.48963374, -0.96276969]]))


## Exercise

A location in 3d Cartesian space may be represented by (x,y,z) coordinates. This may be represented by a
dimension 1 array with size 3.

In the cell below:
* Create a 1d array with three elements to represent Position A, which is at (1,2,1)
* Calculate the location of Position B, which has a displacement of (3,-4,1) from Position A
* Calculate the location of Position C, which is twice as far from the origin as Position B
* Calculate the location of position D, which is found by rotating position C $45^{o}$ around the z axis (clockwise
when viewed from above). To rotate a location around the z axis in this manner by an angle $\theta$, it may be
multiplied by the matrix:
$
\begin{pmatrix}
\cos(\theta) & -\sin(\theta) & 0 \\ 
\sin(\theta) & \cos(\theta) & 0 \\ 
0 & 0 & 1
\end{pmatrix}
$
* Calculate the straight line distance between Position D and the origin

In [11]:
a = np.array([1,2,1])
print(a)
b = a + np.array([3,-4,1])
print(b)
c = 2 * b
print(c)
d = np.matmul(np.array([[np.cos(np.pi/4),-np.sin(np.pi/4),0],[np.sin(np.pi/4),np.cos(np.pi/4),0],[0,0,1]]),c)
print(d)
distance = np.sqrt(np.dot(d,d))
print(distance)

[1 2 1]
[ 4 -2  2]
[ 8 -4  4]
[8.48528137 2.82842712 4.        ]
9.797958971132713


In [12]:
#@title
import numpy as np
import math

# Define Position A
pos_a = np.array([1,2,1])
print("Poition A: ", pos_a)

# Add the specified displacement to position A to get position B
pos_b = pos_a + np.array([3,-4,1])
print("Position B: ", pos_b)

# Double the values in position B to get position C
pos_c = pos_b * 2
print("Position C: ", pos_c)

# Calcualte 45 degrees in radians
radians_45 = 45 * math.pi / 180
# Create the rotation matrix
rotation_matrix = np.array([[math.cos(radians_45), -math.sin(radians_45), 0], [math.sin(radians_45), math.cos(radians_45), 0], [0,0,1]])
print("Rotation matrix: ", rotation_matrix)
# Operate of position C with the rotation matrix to get position D
pos_d = np.matmul(rotation_matrix, pos_c)
print("Position D: ", pos_d)

# Calcualte the distance between position D and the origin
distance_d = math.sqrt(np.dot(pos_d, pos_d))
print("Distance: ", distance_d)

Poition A:  [1 2 1]
Position B:  [ 4 -2  2]
Position C:  [ 8 -4  4]
Rotation matrix:  [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Position D:  [8.48528137 2.82842712 4.        ]
Distance:  9.797958971132713


## Extension: Solving Matrix Equations and Sparse Matrices

Sometimes it can be desirable to solve a matrix equation of the form $Mx=b$ where $M$ is a matrix, $b$ is a known vector and $x$ is an unknown vector whose value is to be found. For instance, consider the equation:

$$\begin{pmatrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 1
\end{pmatrix}
\vec{x}
=
\begin{pmatrix}
4\\ 
5\\ 
10
\end{pmatrix}$$

We can use the ```linalg.solve``` function to solve an equation of this type as follows:

In [ ]:
import numpy as np

m = np.array([[1,2,3], [2,1,0], [4,2,1]])
b = np.array([4,5,10])

x = np.linalg.solve(m, b)

print(x)

However, this function becomes slower and slower as the size of matrix gets larger. For a particular type of matrix that contains mostly zeros, this can be sped up by storing the matrix as a sparse matrix. This means that only non-zero values will be stored and only these non-zero values will be used in calculations. This dramatically reduces memory usage and the computational cost of the solving the matrix equation. There are may [types of sparse matrix included in SciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html), but we will pick the [compressed row storage matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix) for this example (see [here](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format) for a rough description of how this works). The matrix we will solve for will have the value of 1 along the central diagonal and -0.5 on the adjacent diagonals. The array on the left-hand side will have a value of 1.

There are [many sovlers](https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html) included to be used with sparse matrices. Which one to use is not always a simple question. For this example we'll use the [conjugate gradient solver](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html#scipy.sparse.linalg.cg) (see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html#scipy.sparse.linalg.cg) for a description of how this method works).

In [ ]:
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import cg

# Provide the dimensions of the matrix as a tuple
m = csr_matrix((1000, 1000))

# Write values to the lead diagonal
for i in range(1000):
  m[i,i] = 1

# Write values to the diagonals next to the lead diagonal
for i in range(999):
  m[i, i+1] = -0.5
  m[i+1, i] = -0.5

print("M:")
# When we print the matrix, the coordinates of the non-zero values and their values will be printed
print(m)

b = np.zeros(1000) + 1
print("B: ", b)

x = cg(m, b)

# Note the zero that is included in the tuple that was returned is an integer which indicates teh conjugate gradient solver converged correctly and found a solution
print("X: ", x)

This is an example of how Scipy can be used to solve linear algebra problems efficiently.