# Creating and Manipulating NumPy Arrays

## Arrays

One of the most important constructs in NumPy is the ```array```. To create an array, we first need to import the NumPy module into our code. When we do this, it is common to give it the alias ```np```. We can then create an array by writing ```np.array()``` and providing a sequence (such as a list or tuple) of values.

In [1]:
import numpy as np

my_array = np.array([1, 2, 3])

## Printing Arrays

We can print arrays as normal using the print statement:

In [2]:
print(my_array)

print([1, 2, 3])

[1 2 3]
[1, 2, 3]


Note that, when we print an array, it is printed within square brackets and without commas separating values, whilst a list is printed with commas. This allows us to easily distinguish these data types when they're printed.

### Array Data Types

The elements of an array must all the same type. So we can create an array of strings or bools:

In [3]:
import numpy as np

string_array = np.array(["str1", "str2"])
print(string_array)

bool_array = np.array([True, False])
print(bool_array)

['str1' 'str2']
[ True False]


However, if we try to define an array with a mixture of types, NumPy will try to convert some or all of the values so that all values have the same type.

In [4]:
import numpy as np

mixed_array = np.array([1, 1.2])
print(mixed_array) # Both values are converted to floats

mixed_array2 = np.array([4, "str"])
print(mixed_array2) # Both values are converted to strings

[1.  1.2]
['4' 'str']


We can check the type of data stored in an array using the ```dtype``` property:

In [5]:
import numpy as np

array1 = np.array([1, 2])
print(array1.dtype)

array2 = np.array([True, False])
print(array2.dtype)

array3 = np.array(["1", "2"])
print(array3.dtype)

array4 = np.array(["1234567890", "2"])
print(array4.dtype)

array5 = np.array([1.0, -2.0])
print(array5.dtype)

int32
bool
<U1
<U10
float64


Note that the data types reported are different to normal Python data types - these are the types which NumPy uses to store the data. For instance, ```int64``` describes as 64-bit integer, ```<U1``` describes a one-character string and ```float64``` describes a 64 bit float.

## Arrays with Multiple Dimensions

It's also possible to create arrays with multiple dimensions. We can do this using the ```array``` function. If we passed a sequence of sequences to this function, the returned value will be a two dimensional array. A sequence of sequences of sequences would produce a three-dimensional array and so on.

We can find the dimension of a NumPy array by using its ```ndim``` property and the extent of an array in each dimension using the ```shape``` property.

In [6]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])

print(a)
print(a.ndim)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


Note that, when creating a multi-dimensional array, the size of the resultant array must be consistent in each dimension (i.e. you cannot create a "ragged" array). As an example, each row of a two-dimensional array must have the same number of entries, otherwise an error will be returned:

In [7]:
import numpy as np

a = np.array([[1], [3,4]])

C:\Users\thoma\AppData\Local\Temp\ipykernel_40412\2585536774.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1], [3,4]])


### Zeros

It's also possible to create an array of zeros using the ```zeros``` function. As an argument, this accepts a sequence of integers which specify the size of the array to be created in each dimension. As a result, the number of entries in the sequence defines the number of dimensions in the array.

The following creates an array with 3 dimensions and a size of two in the first two dimensions and a size of three in the third dimension.

In [8]:
import numpy as np

zero = np.zeros([2,2,3])

print(zero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


Note that, as the number of dimensions increase it becomes progressively more difficult to interpret the data stored within an array by printing all of it, although NumPy does its best to present it in a helpful way.

### Full

It's possible to create a new array with all values being the same using the ```full``` function, which works in a similar way to the ```zeros``` function. The first argument is a sequence which defines the size of the array in as many dimensions as the array has entries.

In [9]:
import numpy as np

# Create an array with 2 rows and 3 columns
# All entries have a value of 1
a = np.full([2,3], 1)
print(a)

[[1 1 1]
 [1 1 1]]


### Arange

The ```arange``` function works in a similar way to the ```range``` function, but returns a NumPy array containing the values specified:

In [10]:
import numpy as np

a = np.arange(3, 11, 2)

print(a)

[3 5 7 9]


### Reshape

It's also possible to use the ```reshape``` method of an array to create a version of an an array with a different shape (and, potentially, a different number of dimensions). For instance, here we will create an one-dimensional array with 12 entries using ```arange``` before reshaping it to be a three-dimensional array with sizes in each dimension of 2, 2 and 3.

In [11]:
a = np.arange(12).reshape([2,2,3])

print(a.ndim)
print(a.shape)
print(a)

3
(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


The new shape of the array must contain the same number of entries as the original shape. For instance, the following will fail:

In [12]:
import numpy as np

a = np.arange(7).reshape([2,3])

ValueError: cannot reshape array of size 7 into shape (2,3)

### Exercise

In the code cell below, do the following:

* Create a one-dimensional array with a series of three bools of your choice
* Create a three-dimensional array with every value being equal to zero. This array should have a size of 4 in dimension 1, a size of 3 in dimension 2 and a size of 2 in dimension 3
* Create an array of the same dimension and size with the values 0-23 (inclusive)

##### Extension

* Create an array of the same dimension and size with the values every other value from 4-50 (inclusive)

In [20]:
a = np.array([True, True, False])
b = np.zeros([4,3,2])
c = np.arange(0,24).reshape([4,3,2])
d = np.arange(4,51,2).reshape([4,3,2])
print(a)
print(b)
print(c)

[ True  True False]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [17]:
#@title

# Import NumPy
import numpy as np

# Create the 1D array
bools = np.array([True, False, True])
print(bools)

# Create the array of zeros
a = np.zeros([4,3,2])
print(a)

# Print a blank line to separate the arrays in the output
print("")

# Create the array with the increasing numbers
b = np.arange(24).reshape([4,3,2])
print(b)

# Print a blank line to separate the arrays in the output
print("")

# Extension exercise
c = np.arange(4, 51, 2).reshape([4,3,2])
print(c)

[ True False  True]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[[ 4  6]
  [ 8 10]
  [12 14]]

 [[16 18]
  [20 22]
  [24 26]]

 [[28 30]
  [32 34]
  [36 38]]

 [[40 42]
  [44 46]
  [48 50]]]


## Selecting Items from an Array

To select single items from an array, we provide the indices in each dimension of the item, separated by commas within a set of square brackets.

In [21]:
import numpy as np

a = np.arange(10).reshape([2,5])

print(a[1,3])

8


It's possible to select multiple items from an array in much the same way as it's possible with a string or list.

In [22]:
import numpy as np

a = np.arange(10)

print(a[1:9:2])

[1 3 5 7]


It's also possible to do this for arrays with multiple dimensions with the specifications of indices for each separated with commas. If the specification of the indices for a dimension is purely a colon, every possible index from that dimension is used for the returned data.

In [23]:
import numpy as np

a = np.arange(12).reshape([2,2,3])
print(a)

b = a[0, :, 0::2]
#Because only one index was selected for dimension 1, b will be 2D rather than 3D
print(b.ndim)
print("b")
print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
2
b
[[0 2]
 [3 5]]


If we provide a single value followed by a colon in the position for one dimension, every index beginning with that value will be selected. If we put the olon first, every index before the following value will be selected.

In [24]:
import numpy as np

# Same a as previous example
a = np.arange(12).reshape([2,2,3])
print(a)

b = a[:1, 0, 1:]
print("b")
print(b)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
b
[[1 2]]


## Assigning to Items in an Array

It's possible to change the values inside an array using item assignment, selecting which items to assign to using the same notation as in the previous section. If a single value is provided on the right-hand side of the assignment operator then every specified location in the array will be given that value.

In [26]:
import numpy as np

a = np.arange(12).reshape([2,2,3])
a[1,1,2] = 50
a[0,:,0::2] = 40

print(a)

[[[40  1 40]
  [40  4 40]]

 [[ 6  7  8]
  [ 9 10 50]]]


If, instead another array is on the right-hand side of the assignment operator, the values of that array will be assigned to the location in the array on the left-hand side of the assignment operator. Assignment in this way requires that the array on the right-hand side and the selected locations from the array on the left-hand side have the same dimension and size.

In [27]:
import numpy as np

a = np.zeros([4, 2, 3])

a[0,:,0::2] = np.arange(1,5).reshape([2,2])

print(a)

[[[1. 0. 2.]
  [3. 0. 4.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


## Exercise

* Create a 2-D array from the array below, using the values with the lowest two indices from the first dimension, the highest two indices from the second dimension and only the first index of the third dimension. This array should have the values ```[[6, 8] [16, 18]]```.
* In this new array, modify the array with indices ```[1, 1]``` to have the value ```4```.
* Also in the new array, modify the values which have an index of 0 in the first dimension to have the values ```[1,2]``` using a single assignment statement.

In [33]:
import numpy as np

start_array = np.arange(30).reshape([3,5,2])

a = start_array[:2,-2:,0]
print(a)
a[1,1]=4
print(a)
a[0,:]=np.array([1,2])
print(a)

[[ 6  8]
 [16 18]]
[[ 6  8]
 [16  4]]
[[ 1  2]
 [16  4]]


In [34]:
#@title
start_array = np.arange(30).reshape([3,5,2])

# Print the initial array for reference
print(start_array)
# Print a blank line to separate the arrays
print(" ")
a = start_array[:2,3:,0]
print(a)

# Print a blank line to separate the arrays
print(" ")
a[1,1] = 4
print(a)

# Print a blank line to separate the arrays
print(" ")
a[0,:] = np.array([1,2])
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
 
[[ 6  8]
 [16 18]]
 
[[ 6  8]
 [16  4]]
 
[[ 1  2]
 [16  4]]
